[project]
name = "fasco-shop"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "djangorestframework>=3.16.1",
    "flake8>=7.3.0",
    "isort>=6.1.0",
    "psycopg2-binary>=2.9.10",
]
